[phases.setup]
  nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
  cmds = ["npm install"]

[phases.build]
  cmds = ["echo 'Build completed'"]

[start]
  cmd = "npm start"

[variables]
  NODE_ENV = "production"
  PORT = "8000"

[phases.setup.nixPkgs]
  nodejs = "18_x"
  npm = "9_x"
