[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3

[env]
  NODE_ENV = "production"
  PORT = "8000"

[nixpacks]
  installCommand = "npm install"
  startCommand = "npm start"
  phases.install.cmds = ["npm install"]
  phases.build.cmds = ["echo 'Build completed'"]
  start.cmd = "npm start"
