[build]
  builder = "dockerfile"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3

[env]
  NODE_ENV = "production"
  NODE_VERSION = "18.19.0"

[railway]
  rootDirectory = "backend"
